'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { scan, makeId, areaOf } = require('../lib/scan');

const texts = (code, opts) => scan(code, opts).entries.map((e) => e.en);

test('문장형 문자열을 추출한다', () => {
  assert.deepEqual(texts('f("Hello world, hacker.");'), ['Hello world, hacker.']);
});

test('식별자형/소문자 단어/경로/클래스명은 제외하고 대문자 단어는 포함한다', () => {
  assert.deepEqual(texts('f("hack","a/b.js","flex center","Hacking");'), ['Hacking']);
});

test('비교에 쓰인 텍스트는 다른 위치에서도 보호된다', () => {
  const r = scan('if (x === "Hacking") {} f("Hacking"); f("Server name");');
  assert.deepEqual(r.entries.map((e) => e.en), ['Server name']);
  assert.ok(r.protectedTexts.has('Hacking'));
});

test('switch case, in 연산자, 객체 키, computed 멤버는 보호된다', () => {
  const code = 'switch(x){case "Some case text": break;} o={"Some Key": "Some value"}; o["Other Key"]; ("In Key" in o);';
  assert.deepEqual(texts(code), ['Some value']);
});

test('includes/get 등 키 조회 메서드의 첫 인자와 배열 룩업은 보호된다', () => {
  const code = 'a.includes("Some text here"); ["List item one","List item two"].includes(x); f("Some text here"); f("Free text one");';
  assert.deepEqual(texts(code), ['Free text one']);
});

test('use strict 지시문은 제외한다', () => {
  assert.deepEqual(texts('"use strict"; f("Hello world");'), ['Hello world']);
});

test('식 있는 템플릿은 {n} 플레이스홀더 텍스트와 식 소스를 가진다', () => {
  const [e] = scan('f(`You have ${n + 1} servers`);').entries;
  assert.equal(e.en, 'You have {0} servers');
  assert.equal(e.kind, 'template');
  assert.deepEqual(e.exprs, ['n + 1']);
});

test('태그드 템플릿은 제외한다', () => {
  assert.deepEqual(texts('css`Some thing here`;'), []);
});

test('sourceOf가 null이면 제외하고, 경로면 area를 붙인다', () => {
  assert.deepEqual(texts('f("Hello world");', { sourceOf: () => null }), []);
  const [e] = scan('f("Hello world");', { sourceOf: () => 'Terminal/Terminal.ts' }).entries;
  assert.equal(e.source, 'Terminal/Terminal.ts');
  assert.equal(e.area, 'ui');
});

test('areaOf는 경로로 영역을 정한다', () => {
  assert.equal(areaOf('Documentation/pages.ts'), 'docs');
  assert.equal(areaOf('Literature/Literatures.tsx'), 'story');
  assert.equal(areaOf('Augmentation/Augmentations.ts'), 'game');
  assert.equal(areaOf('Terminal/Terminal.ts'), 'ui');
  assert.equal(areaOf(null), 'ui');
});

test('monospace 폰트 스택은 번역 후보가 아니라 fontEdits로 나온다', () => {
  const r = scan('f("Lucida Console, monospace");');
  assert.deepEqual(r.entries, []);
  assert.equal(r.fontEdits.length, 1);
  assert.equal(r.fontEdits[0].text, '"\\"D2Coding KO\\", Lucida Console, monospace"');
});

test('makeId는 12자리 hex이고 결정적이다', () => {
  assert.match(makeId('abc'), /^[0-9a-f]{12}$/);
  assert.equal(makeId('abc'), makeId('abc'));
  assert.notEqual(makeId('abc'), makeId('abd'));
});

test('Monaco 기본 폰트 설정값에도 D2Coding KO를 앞에 붙인다', () => {
  const r = scan('o={MonacoFontFamily:"JetBrainsMono",MonacoFontSize:20};');
  assert.equal(r.fontEdits.length, 1);
  assert.equal(r.fontEdits[0].text, '"\\"D2Coding KO\\", JetBrainsMono"');
});

test('exclude.sources 정규식에 맞는 소스 파일의 문자열은 제외한다', () => {
  const opts = {
    sourceOf: () => 'Augmentation/Enums.ts',
    exclude: { sources: ['Enums\.ts$'] },
  };
  assert.deepEqual(texts('f("Hello world");', opts), []);
  const ok = { sourceOf: () => 'Terminal/Terminal.ts', exclude: opts.exclude };
  assert.deepEqual(texts('f("Hello world");', ok), ['Hello world']);
});

test('exclude.include에 있는 텍스트는 휴리스틱에 걸려도 번역 후보가 된다 (보호 문맥은 여전히 제외)', () => {
  const opts = { exclude: { include: ['overwrite', 'completely wipe'] } };
  assert.deepEqual(texts('f("overwrite"); g("completely wipe");', opts), ['overwrite', 'completely wipe']);
  assert.deepEqual(texts('f("overwrite");'), []);
  assert.deepEqual(texts('if (x === "overwrite") {} f("overwrite");', opts), []);
});

test('식별자 속성 키/멤버 이름과 같은 텍스트는 어디서든 보호된다', () => {
  assert.deepEqual(texts('const O={Hack:()=>1,Str:()=>2}; f("Hack"); f("Str"); f("Free text one");'), ['Free text one']);
  assert.deepEqual(texts('Page.Terminal; f("Terminal"); f("Other label");'), ['Other label']);
  const r = scan('class A { Hacking = 1 } f("Hacking");');
  assert.deepEqual(r.entries, []);
});

test('x.exports = "<마크다운>" 모듈은 docs 영역 항목으로 추출된다 (제목이 source)', () => {
  const r = scan('module.exports = "# Intro\\n\\nHello world, this is a doc page.\\n";');
  assert.equal(r.entries.length, 1);
  assert.equal(r.entries[0].area, 'docs');
  assert.equal(r.entries[0].source, 'doc:Intro');
  assert.equal(r.entries[0].en, '# Intro\n\nHello world, this is a doc page.\n');
});

test('API Documenter 자동 생성 문서와 마크다운이 아닌 exports 문자열은 제외한다', () => {
  assert.deepEqual(texts('e.exports = "<!-- Do not edit this file. It is automatically generated by API Documenter. -->\\n\\n## X\\n";'), []);
  assert.deepEqual(texts('e.exports = "data:image/svg+xml;base64,AAAA";'), []);
});

test('## 로 시작하는 마크다운도 문서로 인식한다', () => {
  const r = scan('e.exports = "## Programs\\n\\nIn Bitburner programs are files.\\n";');
  assert.equal(r.entries[0].source, 'doc:Programs');
});
test('식별자형 단어에 변수를 이어 붙여 만드는 키 접두사("BitNode"+n)는 보호된다', () => {
  assert.deepEqual(texts('const k = "BitNode" + n; const o = M[k];'), []);
  assert.deepEqual(texts('const k = n + "Suffix"; f(k);'), []);
  // 문장/라벨(공백 포함)이나 리터럴끼리의 연결은 그대로 번역 대상
  assert.deepEqual(texts('f("Total money: " + n);'), ['Total money: ']);
});
